[package]
name = "gramex-macro"
description = "gramex proc macro"
version = "0.1.0"
edition = "2024"
readme = "./readme.md"
license = "MIT"
repository = "https://github.com/aliibrahim123/gramex"
documentation = "https://docs.rs/gramex/"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
chunked-quote = "0.1.5"
rustc-hash = "2.1.3"
