[package]
name = "gramex"
description = "common language for advance parsers"
edition = "2024"
version = "0.1.1"
readme = "../readme.md"
license = "MIT"
repository = "https://github.com/aliibrahim123/gramex"
documentation = "https://docs.rs/gramex/"

[lib]
doctest = false

[features]
default = ["std"]
std = []
str = []
bin = []


[dependencies]
gramex-macro = { version = "0.1.0", path = "../macro" }
lean_string = "0.7.0"
